[package]
name = "simplex"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.58"

[dependencies.inkwell]
version = "0.4.0"
features = ["llvm16-0-prefer-dynamic"]

[dependencies.lalrpop-util]
version = "0.20.0"
features = ["lexer", "unicode"]

[build-dependencies]
lalrpop = "0.20.0"
